# Generated by Django 4.2.6 on 2024-09-18 20:12

import apps.api.news.models.news
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='Заголовок')),
                ('publish_date', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('update_date', models.DateField(auto_now=True, verbose_name='Дата изменения')),
                ('text', models.TextField(verbose_name='Контент')),
                ('image', models.ImageField(blank=True, upload_to=apps.api.news.models.news.News.upload_path, verbose_name='Изображение для новости')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-id'],
            },
        ),
    ]
