# Generated by Django 4.2.6 on 2024-09-18 20:12

import apps.api.event.models.event
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to=apps.api.event.models.event.Event.upload_path, verbose_name='Картинка мероприятия')),
                ('date', models.DateTimeField(verbose_name='Дата мероприятия')),
                ('address', models.CharField(max_length=64, verbose_name='Адрес мероприятия')),
                ('landmark', models.CharField(blank=True, max_length=100, verbose_name='Ориентир')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_event', to='event.event', verbose_name='Мероприятие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_event', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Мероприятие пользователя',
                'verbose_name_plural': 'Мероприятия пользователей',
                'unique_together': {('user', 'event')},
            },
        ),
    ]
