# Generated by Django 4.2.6 on 2024-09-16 07:32

import apps.api.event.models.event
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0002_userevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userevent',
            options={'verbose_name': 'Мероприятие пользователя', 'verbose_name_plural': 'Мероприятия пользователей'},
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, upload_to=apps.api.event.models.event.Event.upload_path, verbose_name='Картинка мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='landmark',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ориентир'),
        ),
        migrations.AlterUniqueTogether(
            name='userevent',
            unique_together={('user', 'event')},
        ),
    ]
